import sys, os
sys.path.insert(0, os.path.expanduser('~/MetaboLC-app'))

from backend.database import SessionLocal, engine
from backend.models import Base, Method, GradientStep, MRMTransition

Base.metadata.create_all(bind=engine)

METHODS = [
    {
        "method": {
            "title": "93 drug compounds in human urine",
            "analyte": "Multi-drug panel (93 compounds: amphetamines, opioids, cannabinoids, benzodiazepines)",
            "matrix": "urine",
            "clinical_application": "Toxicology / Drugs of Abuse",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Phenomenex",
            "column_name": "Kinetex Phenyl-Hexyl",
            "column_stationary_phase": "Phenyl-Hexyl",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 2.6,
            "mobile_phase_a": "Ammonium formate in water",
            "mobile_phase_b": "Formic acid in methanol",
            "injection_volume_ul": 5,
            "sample_prep_method": "Enzymatic Hydrolysis",
            "sample_prep_details": "500 uL urine hydrolyzed with IMCS Rapid Hydrolysis Buffer and IMCSzyme 30-60 min at 55C. Add 200 uL MeOH/water, centrifuge 10 min 21000xg.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "notes": "Polarity switching 50ms ESI+/-. Analyst MD v1.6.3.",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
        ],
        "transitions": [
            {"compound_name": "6-MAM", "precursor_mz": 328.1, "product_mz": 165.0, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Amphetamine", "precursor_mz": 136.1, "product_mz": 119.0, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Methamphetamine", "precursor_mz": 150.1, "product_mz": 119.0, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Morphine", "precursor_mz": 286.2, "product_mz": 165.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Codeine", "precursor_mz": 300.2, "product_mz": 165.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Benzoylecgonine", "precursor_mz": 290.1, "product_mz": 168.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Methadone", "precursor_mz": 310.2, "product_mz": 265.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "THC-COOH", "precursor_mz": 343.2, "product_mz": 299.2, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Cortisol and cortisone in human urine (dilute and shoot)",
            "analyte": "Cortisol and Cortisone",
            "analyte_cas": "50-23-7",
            "matrix": "urine",
            "clinical_application": "Endocrinology / Cushing syndrome",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Water + 0.1% formic acid",
            "mobile_phase_b": "Methanol + 0.1% formic acid",
            "injection_volume_ul": 5,
            "sample_prep_method": "Dilute and Shoot",
            "sample_prep_details": "Dilute urine 1:10 with water/methanol 90:10 + IS. Inject directly.",
            "lloq": 1.0,
            "cv_intra_percent": 4.5,
            "cv_inter_percent": 6.2,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 3.0, "percent_b": 80, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 4.5, "percent_b": 80, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 4.6, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 6.0, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "Cortisol", "precursor_mz": 363.2, "product_mz": 121.1, "retention_time_min": 2.9, "collision_energy_ev": 30, "declustering_potential": 80, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Cortisol (qualifier)", "precursor_mz": 363.2, "product_mz": 97.1, "retention_time_min": 2.9, "is_quantifier": 0, "is_internal_standard": 0},
            {"compound_name": "Cortisone", "precursor_mz": 361.2, "product_mz": 163.1, "retention_time_min": 2.5, "collision_energy_ev": 28, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Cortisol-d4 (IS)", "precursor_mz": 367.2, "product_mz": 121.1, "is_quantifier": 1, "is_internal_standard": 1},
        ]
    },
    {
        "method": {
            "title": "Cortisol and cortisone in human urine (SPE)",
            "analyte": "Cortisol and Cortisone",
            "analyte_cas": "50-23-7",
            "matrix": "urine",
            "clinical_application": "Endocrinology / Cushing syndrome",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Water + 0.1% formic acid",
            "mobile_phase_b": "Methanol + 0.1% formic acid",
            "injection_volume_ul": 10,
            "sample_prep_method": "Solid Phase Extraction (SPE)",
            "sample_prep_details": "SPE on C18 or MCX cartridge. Load diluted urine, wash water, elute methanol. Evaporate and reconstitute.",
            "lloq": 0.5,
            "cv_intra_percent": 3.8,
            "cv_inter_percent": 5.1,
            "recovery_percent": 88,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 3.0, "percent_b": 80, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 4.5, "percent_b": 80, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 4.6, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 6.0, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "Cortisol", "precursor_mz": 363.2, "product_mz": 121.1, "retention_time_min": 2.9, "collision_energy_ev": 30, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Cortisone", "precursor_mz": 361.2, "product_mz": 163.1, "retention_time_min": 2.5, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Cortisol-d4 (IS)", "precursor_mz": 367.2, "product_mz": 121.1, "is_quantifier": 1, "is_internal_standard": 1},
        ]
    },
    {
        "method": {
            "title": "Panel of steroid hormones in human serum",
            "analyte": "Steroid panel: testosterone, estradiol, progesterone, cortisol, DHEA-S, androstenedione",
            "matrix": "serum",
            "clinical_application": "Endocrinology / Reproductive hormones",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Water + 0.1% formic acid",
            "mobile_phase_b": "Methanol + 0.1% formic acid",
            "injection_volume_ul": 10,
            "sample_prep_method": "Liquid-Liquid Extraction (LLE)",
            "sample_prep_details": "LLE with MTBE from 200 uL serum. Vortex 5 min, centrifuge, transfer organic layer. Evaporate N2. Reconstitute in 100 uL MP A/B 80:20.",
            "lloq": 0.02,
            "cv_intra_percent": 5.2,
            "cv_inter_percent": 7.8,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 30, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 4.0, "percent_b": 95, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 6.0, "percent_b": 95, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 6.1, "percent_b": 30, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 8.0, "percent_b": 30, "flow_rate_ml_min": 0.4, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "Testosterone", "precursor_mz": 289.2, "product_mz": 97.1, "retention_time_min": 4.2, "collision_energy_ev": 25, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Testosterone-d3 (IS)", "precursor_mz": 292.2, "product_mz": 100.1, "is_quantifier": 1, "is_internal_standard": 1},
            {"compound_name": "Androstenedione", "precursor_mz": 287.2, "product_mz": 97.1, "retention_time_min": 3.9, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Cortisol", "precursor_mz": 363.2, "product_mz": 121.1, "retention_time_min": 2.8, "collision_energy_ev": 30, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Cortisone", "precursor_mz": 361.2, "product_mz": 163.1, "retention_time_min": 2.5, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "DHEA-S", "precursor_mz": 367.2, "product_mz": 97.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Progesterone", "precursor_mz": 315.2, "product_mz": 109.1, "retention_time_min": 4.8, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "25-OH-Vitamin D3, 3-epi-25-OH-Vitamin D3 and 25-OH-Vitamin D2 in human plasma",
            "analyte": "Vitamin D panel (25-OH-D3, 3-epi-25-OH-D3, 25-OH-D2)",
            "matrix": "plasma",
            "clinical_application": "Vitamin D deficiency / Endocrinology",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 100,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Water + methanol + formic acid",
            "mobile_phase_b": "Methanol + formic acid",
            "injection_volume_ul": 10,
            "sample_prep_method": "Protein Precipitation (PPT)",
            "sample_prep_details": "PPT with ACN/MeOH 1:1. Vortex 1 min, centrifuge 5 min 14000 rpm. Dilute 1:1 with MP A.",
            "lloq": 2.5,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "notes": "Separation of 25-OH-D3 from 3-epi epimer critical. BEH C18 provides baseline separation.",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 0.5, "percent_b": 80, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 6.0, "percent_b": 99, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 7.5, "percent_b": 99, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 7.6, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 10.0, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "25-OH-Vitamin D3", "precursor_mz": 401.3, "product_mz": 383.3, "retention_time_min": 5.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "3-epi-25-OH-Vitamin D3", "precursor_mz": 401.3, "product_mz": 383.3, "retention_time_min": 4.8, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "25-OH-Vitamin D2", "precursor_mz": 413.3, "product_mz": 395.3, "retention_time_min": 4.5, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "25-OH-Vitamin D3-d6 (IS)", "precursor_mz": 407.3, "product_mz": 389.3, "is_quantifier": 1, "is_internal_standard": 1},
        ]
    },
    {
        "method": {
            "title": "Immunosuppressants in human whole blood (tacrolimus, cyclosporin A, sirolimus, everolimus)",
            "analyte": "Immunosuppressant panel",
            "matrix": "whole blood",
            "clinical_application": "Therapeutic Drug Monitoring / Transplant",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Ammonium acetate + zinc sulfate in water/methanol",
            "mobile_phase_b": "Ammonium acetate in methanol",
            "injection_volume_ul": 10,
            "sample_prep_method": "Protein Precipitation (PPT)",
            "sample_prep_details": "PPT whole blood with MeOH/zinc sulfate. Vortex, centrifuge. Dilute supernatant before injection.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "notes": "Ammonium adducts [M+NH4]+. Zinc sulfate critical for PPT.",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 50, "flow_rate_ml_min": 0.6, "curve": "linear"},
            {"time_min": 1.5, "percent_b": 95, "flow_rate_ml_min": 0.6, "curve": "linear"},
            {"time_min": 3.5, "percent_b": 95, "flow_rate_ml_min": 0.6, "curve": "linear"},
            {"time_min": 3.6, "percent_b": 50, "flow_rate_ml_min": 0.6, "curve": "linear"},
            {"time_min": 5.0, "percent_b": 50, "flow_rate_ml_min": 0.6, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "Tacrolimus (FK506)", "precursor_mz": 821.5, "product_mz": 768.5, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Cyclosporin A", "precursor_mz": 1220.8, "product_mz": 1203.7, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Sirolimus", "precursor_mz": 931.5, "product_mz": 864.5, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Everolimus", "precursor_mz": 975.6, "product_mz": 908.6, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Ascomycin (IS)", "precursor_mz": 809.5, "product_mz": 756.5, "is_quantifier": 1, "is_internal_standard": 1},
        ]
    },
    {
        "method": {
            "title": "Tricyclic antidepressants and metabolites in human serum",
            "analyte": "TCA panel: amitriptyline, nortriptyline, clomipramine, imipramine, desipramine, clozapine",
            "matrix": "serum",
            "clinical_application": "Therapeutic Drug Monitoring / Psychiatry",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Ammonium formate + formic acid in water",
            "mobile_phase_b": "Ammonium formate + formic acid in MeOH/ACN",
            "sample_prep_method": "Protein Precipitation (PPT)",
            "sample_prep_details": "PPT with ACN/MeOH. Centrifuge and dilute supernatant.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
        ],
        "transitions": [
            {"compound_name": "Amitriptyline", "precursor_mz": 278.2, "product_mz": 233.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Nortriptyline", "precursor_mz": 264.2, "product_mz": 233.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Clomipramine", "precursor_mz": 315.1, "product_mz": 270.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Imipramine", "precursor_mz": 281.2, "product_mz": 86.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Desipramine", "precursor_mz": 267.2, "product_mz": 72.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Clozapine", "precursor_mz": 327.1, "product_mz": 270.1, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Neuroleptics in human serum (risperidone, aripiprazole, clozapine, haloperidol, olanzapine, quetiapine)",
            "analyte": "Neuroleptic panel (7 antipsychotics)",
            "matrix": "serum",
            "clinical_application": "Therapeutic Drug Monitoring / Psychiatry",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Ammonium formate in water",
            "mobile_phase_b": "Ammonium formate in methanol",
            "sample_prep_method": "Protein Precipitation (PPT)",
            "sample_prep_details": "PPT serum with acetonitrile. Centrifuge, dilute and inject.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
        ],
        "transitions": [
            {"compound_name": "Risperidone", "precursor_mz": 411.2, "product_mz": 191.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "9-OH-Risperidone", "precursor_mz": 427.2, "product_mz": 207.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Aripiprazole", "precursor_mz": 448.2, "product_mz": 285.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Clozapine", "precursor_mz": 327.1, "product_mz": 270.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Haloperidol", "precursor_mz": 376.1, "product_mz": 165.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Olanzapine", "precursor_mz": 313.2, "product_mz": 256.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Quetiapine", "precursor_mz": 384.2, "product_mz": 253.1, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Antidepressants in human serum (citalopram, fluoxetine, sertraline, venlafaxine and metabolites)",
            "analyte": "Antidepressant panel (12 compounds)",
            "matrix": "serum",
            "clinical_application": "Therapeutic Drug Monitoring / Psychiatry",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Phenomenex",
            "column_name": "Kinetex C18",
            "column_stationary_phase": "C18",
            "sample_prep_method": "Solid Phase Extraction (SPE)",
            "sample_prep_details": "SPE using Diagnotix psychotropic medication kit.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
        ],
        "transitions": [
            {"compound_name": "Citalopram", "precursor_mz": 325.2, "product_mz": 109.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Fluoxetine", "precursor_mz": 310.1, "product_mz": 148.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Sertraline", "precursor_mz": 306.1, "product_mz": 275.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Venlafaxine", "precursor_mz": 278.2, "product_mz": 260.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Mirtazapine", "precursor_mz": 266.2, "product_mz": 195.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Paroxetine", "precursor_mz": 330.2, "product_mz": 192.1, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Fentanyl and 28 fentanyl analogs in human whole blood",
            "analyte": "Fentanyl and analogs (29 compounds)",
            "matrix": "whole blood",
            "clinical_application": "Toxicology / Opioid panel",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Phenomenex",
            "column_name": "Kinetex C18",
            "column_stationary_phase": "C18",
            "injection_volume_ul": 1,
            "sample_prep_method": "Solid Phase Extraction (SPE)",
            "sample_prep_details": "PPT followed by SPE cleanup from whole blood matrix.",
            "lloq": 0.1,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "notes": "63 MRM transitions. LLOQ = 0.1 ng/mL.",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 10, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 8.0, "percent_b": 90, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 12.0, "percent_b": 90, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 12.1, "percent_b": 10, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 14.0, "percent_b": 10, "flow_rate_ml_min": 0.4, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "Fentanyl", "precursor_mz": 337.2, "product_mz": 188.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Carfentanil", "precursor_mz": 395.2, "product_mz": 246.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Sufentanil", "precursor_mz": 387.2, "product_mz": 238.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Alfentanil", "precursor_mz": 417.2, "product_mz": 268.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Norfentanyl", "precursor_mz": 233.2, "product_mz": 84.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Acetyl fentanyl", "precursor_mz": 323.2, "product_mz": 188.1, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Ethyl glucuronide (EtG) and ethyl sulfate (EtS) in human urine",
            "analyte": "EtG and EtS (alcohol biomarkers)",
            "matrix": "urine",
            "clinical_application": "Alcohol biomarkers / Toxicology",
            "ionization_mode": "ESI-",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "SCIEX",
            "column_name": "Analytical column (provided)",
            "column_stationary_phase": "C18",
            "injection_volume_ul": 20,
            "sample_prep_method": "Dilute and Shoot",
            "lloq": 0.1,
            "cv_intra_percent": 3.9,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "notes": "EtG r2=0.9992, EtS r2=0.9993.",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
        ],
        "transitions": [
            {"compound_name": "EtG (Ethyl glucuronide)", "precursor_mz": 220.9, "product_mz": 75.0, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "EtS (Ethyl sulfate)", "precursor_mz": 124.8, "product_mz": 79.9, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Phosphatidylethanol (PEth 16:0/18:1) in human whole blood",
            "analyte": "Phosphatidylethanol 16:0/18:1 (PEth)",
            "matrix": "whole blood",
            "clinical_application": "Alcohol biomarker / Long-term alcohol use",
            "ionization_mode": "ESI-",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Phenomenex",
            "column_name": "Kinetex C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 30,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.6,
            "mobile_phase_a": "Ammonium formate in water/IPA/ACN",
            "mobile_phase_b": "Ammonium formate in IPA/ACN (high organic)",
            "sample_prep_method": "Liquid-Liquid Extraction (LLE)",
            "sample_prep_details": "Add IS to 100 uL whole blood. LLE extraction, evaporation, reconstitution.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 2.0, "percent_b": 99, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 5.0, "percent_b": 99, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 5.1, "percent_b": 20, "flow_rate_ml_min": 0.4, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "PEth 16:0/18:1", "precursor_mz": 701.5, "product_mz": 280.8, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Metanephrines in human serum (metanephrine and normetanephrine)",
            "analyte": "Metanephrine and Normetanephrine",
            "matrix": "serum",
            "clinical_application": "Endocrinology / Pheochromocytoma",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC HSS T3",
            "column_stationary_phase": "C18 T3",
            "column_length_mm": 100,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.8,
            "mobile_phase_a": "Water + HFBA + formic acid",
            "mobile_phase_b": "Acetonitrile + formic acid",
            "injection_volume_ul": 10,
            "sample_prep_method": "Solid Phase Extraction (SPE)",
            "sample_prep_details": "SPE on MCX cartridge. Add IS, load serum, wash water/MeOH, elute NH3/MeOH. Evaporate, reconstitute.",
            "lloq": 0.05,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "notes": "HFBA ion-pairing agent critical for retention of polar compounds.",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 5, "flow_rate_ml_min": 0.3, "curve": "linear"},
            {"time_min": 4.0, "percent_b": 40, "flow_rate_ml_min": 0.3, "curve": "linear"},
            {"time_min": 5.0, "percent_b": 95, "flow_rate_ml_min": 0.3, "curve": "linear"},
            {"time_min": 6.0, "percent_b": 95, "flow_rate_ml_min": 0.3, "curve": "linear"},
            {"time_min": 6.1, "percent_b": 5, "flow_rate_ml_min": 0.3, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "Metanephrine", "precursor_mz": 182.1, "product_mz": 151.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Normetanephrine", "precursor_mz": 168.1, "product_mz": 137.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Metanephrine-d3 (IS)", "precursor_mz": 185.1, "product_mz": 154.1, "is_quantifier": 1, "is_internal_standard": 1},
        ]
    },
    {
        "method": {
            "title": "Methylmalonic acid (MMA) in human serum",
            "analyte": "Methylmalonic acid (MMA)",
            "analyte_cas": "516-05-2",
            "matrix": "serum",
            "clinical_application": "Vitamin B12 deficiency / Metabolic screening",
            "ionization_mode": "ESI-",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC HSS T3",
            "column_stationary_phase": "C18 T3",
            "column_length_mm": 100,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.8,
            "mobile_phase_a": "Water + ammonium acetate",
            "mobile_phase_b": "Methanol + ammonium acetate",
            "injection_volume_ul": 5,
            "sample_prep_method": "Protein Precipitation (PPT)",
            "sample_prep_details": "PPT serum with ACN 1:3. Centrifuge 5 min 14000 rpm. Dilute 1:2 with MP A.",
            "lloq": 0.05,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "notes": "ESI- mode. Succinic acid isomer must be resolved chromatographically.",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
            {"time_min": 0.0, "percent_b": 5, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 2.0, "percent_b": 50, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 3.5, "percent_b": 50, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 3.6, "percent_b": 5, "flow_rate_ml_min": 0.4, "curve": "linear"},
            {"time_min": 5.0, "percent_b": 5, "flow_rate_ml_min": 0.4, "curve": "linear"},
        ],
        "transitions": [
            {"compound_name": "Methylmalonic acid (MMA)", "precursor_mz": 117.0, "product_mz": 73.0, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "MMA-d3 (IS)", "precursor_mz": 120.0, "product_mz": 76.0, "is_quantifier": 1, "is_internal_standard": 1},
        ]
    },
    {
        "method": {
            "title": "Antiretroviral drugs in human plasma (tenofovir, efavirenz, lopinavir, ritonavir, darunavir, atazanavir)",
            "analyte": "Antiretroviral panel (HIV treatment monitoring)",
            "matrix": "plasma",
            "clinical_application": "Therapeutic Drug Monitoring / HIV",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Water + 0.1% formic acid",
            "mobile_phase_b": "Methanol + 0.1% formic acid",
            "injection_volume_ul": 5,
            "sample_prep_method": "Protein Precipitation (PPT)",
            "sample_prep_details": "PPT plasma with ACN 1:3. Centrifuge 5 min 14000 rpm. Dilute before injection.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
        ],
        "transitions": [
            {"compound_name": "Efavirenz", "precursor_mz": 316.0, "product_mz": 244.0, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Lopinavir", "precursor_mz": 629.4, "product_mz": 447.3, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Ritonavir", "precursor_mz": 721.4, "product_mz": 296.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Darunavir", "precursor_mz": 548.2, "product_mz": 392.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Atazanavir", "precursor_mz": 705.4, "product_mz": 168.1, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Antifungals in human plasma (voriconazole, itraconazole, posaconazole, fluconazole)",
            "analyte": "Antifungal panel",
            "matrix": "plasma",
            "clinical_application": "Therapeutic Drug Monitoring / Antifungal therapy",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Waters",
            "column_name": "Acquity UPLC BEH C18",
            "column_stationary_phase": "C18",
            "column_length_mm": 50,
            "column_diameter_mm": 2.1,
            "column_particle_size_um": 1.7,
            "mobile_phase_a": "Water + 0.1% formic acid + 5mM ammonium formate",
            "mobile_phase_b": "Acetonitrile + 0.1% formic acid",
            "injection_volume_ul": 5,
            "sample_prep_method": "Protein Precipitation (PPT)",
            "sample_prep_details": "PPT plasma with ACN 1:3 + IS. Vortex 1 min, centrifuge 5 min 14000 rpm. Dilute 1:2 with MP A.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [
        ],
        "transitions": [
            {"compound_name": "Voriconazole", "precursor_mz": 350.1, "product_mz": 281.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Itraconazole", "precursor_mz": 705.3, "product_mz": 392.2, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Posaconazole", "precursor_mz": 701.4, "product_mz": 683.4, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "Fluconazole", "precursor_mz": 307.1, "product_mz": 238.1, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "Mitragynine and 7-hydroxymitragynine in human urine (Kratom alkaloids)",
            "analyte": "Mitragynine and 7-Hydroxymitragynine",
            "matrix": "urine",
            "clinical_application": "Toxicology / Kratom",
            "ionization_mode": "ESI+",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Phenomenex",
            "column_name": "Kinetex C18",
            "column_stationary_phase": "C18",
            "sample_prep_method": "Enzymatic Hydrolysis",
            "sample_prep_details": "Enzymatic hydrolysis of urine followed by PPT or dilute-and-shoot.",
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [],
        "transitions": [
            {"compound_name": "Mitragynine", "precursor_mz": 399.2, "product_mz": 238.1, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "7-Hydroxymitragynine", "precursor_mz": 415.2, "product_mz": 238.1, "is_quantifier": 1, "is_internal_standard": 0},
        ]
    },
    {
        "method": {
            "title": "11-nor-9-carboxy-THC (THC-COOH) in human hair",
            "analyte": "THC-COOH",
            "analyte_cas": "56030-54-7",
            "matrix": "tissue",
            "clinical_application": "Toxicology / Cannabis chronic use biomarker",
            "ionization_mode": "ESI-",
            "instrument_manufacturer": "Sciex",
            "instrument_model": "Triple Quad 4500MD",
            "column_brand": "Phenomenex",
            "column_name": "Kinetex C18",
            "column_stationary_phase": "C18",
            "sample_prep_method": "Other",
            "sample_prep_details": "Hair decontamination, pulverization, organic solvent extraction. Evaporation and reconstitution.",
            "lloq": 0.2,
            "laboratory": "SCIEX Clinical Diagnostics",
            "country": "USA",
            "reference": "SCIEX 4500MD System Compendium (2025)",
            "notes": "LLOQ = 0.2 pg/mg hair. RT = 4.334 min.",
            "submitted_by": "SCIEX Clinical Diagnostics",
            "status": "verified",
        },
        "gradient": [],
        "transitions": [
            {"compound_name": "THC-COOH", "precursor_mz": 342.9, "product_mz": 245.1, "retention_time_min": 4.334, "is_quantifier": 1, "is_internal_standard": 0},
            {"compound_name": "THC-COOH (qualifier)", "precursor_mz": 342.9, "product_mz": 299.1, "is_quantifier": 0, "is_internal_standard": 0},
        ]
    },
]


def seed():
    db = SessionLocal()
    try:
        existing = db.query(Method).count()
        if existing > 0:
            print(f"Already {existing} methods in DB. Delete metabolc.db to reseed.")
            return
        print(f"Seeding {len(METHODS)} methods...")
        for i, entry in enumerate(METHODS):
            m = Method(**entry["method"])
            db.add(m)
            db.flush()
            for step in entry.get("gradient", []):
                db.add(GradientStep(method_id=m.id, **step))
            for t in entry.get("transitions", []):
                db.add(MRMTransition(method_id=m.id, **t))
            print(f"  [{i+1}/{len(METHODS)}] {entry['method']['analyte'][:50]}")
        db.commit()
        total_t = sum(len(e.get("transitions", [])) for e in METHODS)
        print(f"\nDone! {len(METHODS)} methods, {total_t} MRM transitions added.")
    except Exception as e:
        db.rollback()
        print(f"Error: {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed()
